# Generated by Django 4.2.11 on 2024-06-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('system', models.CharField(max_length=50)),
                ('node_name', models.CharField(max_length=100)),
                ('machine_architecture', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=100)),
                ('cores', models.IntegerField()),
                ('logical_cores', models.IntegerField()),
                ('cpu_frequency', models.FloatField()),
                ('total_memory', models.BigIntegerField()),
                ('total_disk', models.BigIntegerField()),
                ('version', models.CharField(max_length=100)),
                ('releases', models.CharField(max_length=200)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('battery_percentage', models.FloatField()),
                ('uptime', models.BigIntegerField()),
                ('boot_time', models.DateTimeField()),
                ('shutdown_time', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_memory', models.BigIntegerField()),
                ('memory_percentage', models.FloatField()),
                ('cached_memory', models.BigIntegerField()),
                ('swap_total', models.BigIntegerField()),
                ('swap_used', models.BigIntegerField()),
                ('swap_percentage', models.FloatField()),
                ('used_disk', models.BigIntegerField()),
                ('disk_percentage', models.FloatField()),
                ('cpu_load_per_core', models.JSONField()),
                ('net_bytes_sent', models.BigIntegerField()),
                ('net_bytes_recv', models.BigIntegerField()),
                ('active_processes', models.IntegerField()),
                ('gpu_usage_percentage', models.FloatField()),
                ('cpu_temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
        ),
    ]
