# Generated by Django 4.2.11 on 2024-06-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_machine_variabledata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='variabledata',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.machine'),
        ),
    ]
