# Generated by Django 4.2.11 on 2024-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_variabledata_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
